# Generated by Django 4.1.2 on 2022-10-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('social_media_link', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
