# Generated by Django 4.1.2 on 2022-10-27 18:39

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('social_media_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
