# Generated by Django 4.1.2 on 2022-10-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approve the album if its name is not explicit'),
        ),
    ]
